baseurl = "https://example.com"
languageCode = "en"
title = "tuxedoneko"
theme = "tuxedoneko"
copyright = "&copy; 2017 tuxedocat♥"
disqusShortname = "shortname"
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "tuxedocat"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "python", "scala", "sh"]

[[params.social]]
url = "https://github.com/tuxedocat"
iconName = "fa-github"

[[params.social]]
url = "https://gitlab.com/tuxedocat"
iconName = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/tuxedocat"
iconName = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/tuxedocat"
iconName = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
iconName = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/tuxedocat"
iconName = "fa-linkedin-square"
